Redo go install bits

diff --git a/source/zshrc b/source/zshrc
--- a/source/zshrc
+++ b/source/zshrc
@@ -84,39 +84,165 @@ source $ZSH/oh-my-zsh.sh
 # alias zshconfig="mate ~/.zshrc"
 # alias ohmyzsh="mate ~/.oh-my-zsh"
 
+rmPath() {
+  local tgt=${1}
+  PATH=$(printf %s $PATH | awk -v RS=: -v ORS=: 'BEGIN { t="^'${tgt}'$"} $1!~t { print }')
+}
+
 addPath() {
   local tgt=${1}
-  if [ -d "${tgt}" ]; then
+  if [[ -d "${tgt}" ]]; then
     rmPath ${tgt}
     PATH="${tgt}:$PATH"
   fi
 }
 
-setGoVersion() {
-  local sdk="$HOME/sdk"
-  local ver="${1}"
-  local gd="${sdk}/${ver}"
+## -- Go version management
+## Change this if you want to use a different directory
+## $HOME/sdk is compatible with 
+export gosdk=$HOME/sdk
 
-  if [[ -z "$(find ${sdk} -mindepth 1 -print -quit 2>/dev/null)" ]]; then
-    echo "No local go versions found, installing latest version; run: installLatestGo"
-    return
+## Current go version. Blank == none. Defaults to the highest version in $gosdk
+export goversion=$(if [[ -d ${gosdk} ]]; then
+ls ${gosdk} | awk '
+BEGIN { v = 0 }
+{
+    n = split($1,parts,".")
+    num = sprintf("%0.3d%0.3d%0.3d",substr($1,3,1), parts[2], parts[3])
+    if (num > v) {
+        v = num
+    }
+}
+END {
+    if (v == 0) {
+      exit
+    }
+    maj = substr(v,0,3)
+    min = substr(v,4,3)
+    patch = substr(v,7,3)
+    printf "go%d.%d", maj, min
+    if (patch > "000") {
+        printf ".%d", patch
+    }
+    printf "\n"
+}'
+fi)
+
+## downloadGoVersion <version|latest>
+## downloads to $gosdk
+## Pass "latest" to {re,}download the latest version of go
+## Pass a specific version to {re,}download it.
+## Assumes version starts with 'go'. Specify 'go1.16.2', not '1.16.2'
+## Uses $HOME/sdk/.dl
+downloadGoVersion() {
+  local gv="${1}"
+  if [[ -z ${gv} ]]; then
+    echo "downloagGoVersion <version|latest>"
+    return 1
+  fi
+
+  if [[ "${gv}" == "latest" ]]; then
+    gv=$(curl -s https://golang.org/VERSION\?m=text)
+  fi
+
+  local arch=$(uname -m)
+  if [[ "${arch}" == "x86_64" ]]; then
+    arch="amd64"
+  fi
+  local sys=$(uname -s)
+  local sdk=$gosdk
+  local gdt=${sdk}/.dl
+  local gvd=${sdk}/${gv}
+  mkdir -p ${gdt}
+  if [[ -d ${gvd} ]]; then
+    rm -rf ${gvd}
+  fi
+  local url="https://dl.google.com/go/${gv}.${sys:l}-${arch}.tar.gz"
+  curl -s -S --fail ${url} | tar zxf - -C ${gdt}
+  local r=${pipestatus[1]}
+  if [[ ${r} != 0 ]]; then
+    >&2 echo "requested url: ${url}"
+    >&2 echo ""
+    rm -rf ${gdt}
+    return ${r}
+  fi
+  mv ${gdt}/go ${gvd} && echo "${gv} downloaded"
+  rm -rf ${gdt}
+}
+
+setGoVersion() {
+  local ver="${1}"
+  if [[ -z "${ver}" ]]; then
+    echo "setGoVersion <version|latest>"
+    return 1
+  fi
+  if [[ ${ver} == "latest" ]]; then
+    ver=$(curl -s https://golang.org/VERSION\?m=text)
+  fi
+
+  local sdk="${gosdk}"
+  local gd="${sdk}/${ver}"
+  if [[ ! -d ${gd} ]]; then
+    echo "${ver} not found locally, downloading to ${gd}"
+    local downloaded=$(downloadGoVersion ${ver})
+    if [[ -z "${downloaded}" ]]; then
+      >&2 echo "Unable to install ${ver}"
+
+      local sys=$(uname -s)
+      local arch=$(uname -m)
+      if [[ "${arch}" == "x86_64" ]]; then
+        arch="amd64"
+      fi
+      local agv=$(curl -s https://golang.org/dl/\?mode\=json\&include\=all | jq '[ .[] | .files |= map(select(.kind == "archive" and .os == "'${sys:l}'" and .arch == "'${arch}'")) | select((.files | length) == 1)]' )
+      if [[ ${ver} != "latest" && -z "$(echo ${agv} | jq -r '.[] | select(.version == "'${ver}'")')" ]]; then
+        >&2 echo ""
+        >&2 echo "${ver} isn't available for ${sys:l}/${arch}"
+      fi
+      if [[ ! -z ${goversion} ]]; then
+        >&2 echo ""
+        >&2 echo "Current Local Go Version: ${goversion}"
+      fi
+      >&2 echo ""
+      >&2 echo -n "Local versions available: "
+      >&2 echo $(ls ${sdk})
+      >&2 echo ""
+      >&2 echo "Latest version: $(echo $agv | jq -r '.[0].version')"
+      >&2 echo ""
+      >&2 echo -n "All versions available for OS ($sys) & ARCH ($arch): "
+      >&2 echo $(echo $agv | jq -r '.[] | .version')
+      >&2 echo ""
+      return ${rv}
+    fi
+    echo "Success!"
+    ver=$(echo $downloaded | awk '{ print $2 }')
   fi
 
   local gbd="${gd}/bin"
-  if [ -d "${gbd}" ]; then
-    # delete any go sdk path items
-    PATH="${gbd}:$(printf %s $PATH | awk -v RS=: -v ORS=: 'BEGIN { t="^'$HOME'/sdk/go[0-9]\\.[0-9]{1,2}(\\.[0-9]{1,2}){1,2}/bin$" } $1!~t { print }')"
-    addPath "$(go env GOPATH)/bin"
-    echo "set $(go version)"
-  else
-    echo "${ver} not found, install with \"go get golang.org/dl/${ver}; ${ver} download\""
-  fi
+  # delete any go sdk path items
+  PATH="$(printf %s $PATH | awk -v RS=: -v ORS=: 'BEGIN { t="^'$HOME'/sdk/go[0-9]\.[0-9]{1,2}(\.[0-9]{1,2}){1,2}/bin$" } $1!~t { print }')"
+  addPath ${gbd}
+  goversion=${ver}
+  echo "set $(go version | awk '{ print $1, $2, "to", $3, "on", $4 }')"
 }
 
-rmPath() {
-  local tgt=${1}
-  PATH=$(printf %s $PATH | awk -v RS=: -v ORS=: 'BEGIN { t="^'${tgt}'$"} $1!~t { print }')
+rmGoVersion() {
+  local ver="${1}"
+  local gd="${gosdk}/${ver}"
+
+  if [[ -d ${gd} ]]; then
+    rm -rf ${gd} && echo "${ver} removed" && return
+  fi
+  echo "${ver} does not exist locally"
+  return 1
 }
+
+mkdir -p ${gosdk}
+if [[ -z "${goversion}" ]]; then
+  echo -e "No Go SDK installed. Install the latest by running: setGoVersion latest"
+else
+  setGoVersion ${goversion}
+fi
+## / - Go version management
 
 osource() {
   local tgt=${1}
@@ -129,58 +255,6 @@ osource() {
 addPath "/usr/local/sbin"
 addPath "/usr/local/opt/gnu-tar/libexec/gnubin"
 addPath "/usr/local/opt/python/libexec/bin"
-
-## rust
-addPath "$HOME/.cargo/bin"
-
-## golang
-gv=$(ls ~/sdk | awk '
-BEGIN { v = 0 }
-{
-    n = split($1,parts,".")
-    num = sprintf("%0.3d%0.3d%0.3d",substr($1,3,1), parts[2], parts[3])
-    if (num > v) {
-        v = num
-    }
-}
-END {
-    if (num == 0) {
-      exit
-    }
-    maj = substr(num,0,3)
-    min = substr(num,4,3)
-    patch = substr(num,7,3)
-    printf "go%d.%d", maj, min
-    if (patch > "000") {
-        printf ".%d", patch
-    }
-    printf "\n"
-}')
-
-installLatestGo() {
-  local arch=$(uname -m)
-  local sys=$(uname -s)
-  local gv=$(curl -s https://golang.org/VERSION\?m=text)
-
-  if [[ "${arch}" == "x86_64" ]]; then
-    arch="amd64"
-  fi
-
-  curl -s https://dl.google.com/go/${gv}.${sys:l}-${arch}.tar.gz | tar zxf - -C $HOME/sdk && mv $HOME/sdk/go $HOME/sdk/${gv} && setGoVersion ${gv}
-}
-
-mkdir -p $HOME/sdk
-if [[ -z "${gv}" ]]; then
-  arch=$(uname -m)
-  if [[ "${arch}" == "x86_64" ]]; then
-    arch="amd64"
-  fi
-  sys=$(uname -s)
-  gv=$(curl -s https://golang.org/VERSION\?m=text)
-  echo -e "No Go SDK installed. To install the latest run: installLatestGo"
-else
-  setGoVersion ${gv}
-fi
 
 ## rbenv
 addPath "$HOME/.rbenv/bin"
@@ -198,6 +272,9 @@ fi
 unalias gb
 alias gcdr="cd $(git rev-parse --show-toplevel)"
 
+## Work specific
+if [ -f ~/.zshrc.work ]; then source ~/.zshrc.work; fi
+
 ## GPG
 # https://github.com/pstadler/keybase-gpg-github#optional-setting-up-tty
 # https://github.com/keybase/keybase-issues/issues/2798
@@ -211,58 +288,3 @@ osource '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion
 ## One password
 alias opm='eval $(op signin mullers)'
 alias opg='eval $(op signin gobridge)'
-
-## Todoist
-declare -i todoistSyncDelay=60
-export todoistSyncDelay
-declare todoistProject=""
-export todoistProject
-syncTodoist() {
-  declare force=$1
-  declare syncFile="$HOME/.todoist.sync"
-  declare -i now=$(date +'%s')
-  declare -i last=0
-  if [[ -e $syncFile ]]; then
-    last=$(stat -f "%m" -t %s $syncFile)
-  fi
-  declare -i diff=$(( now - last ))
-  if [[ ! -z "$force" ]] || (( diff > $todoistSyncDelay )); then
-    todoist sync
-    touch $syncFile
-  fi
-}
-
-today() {
-  syncTodoist
-  declare -a filter=(today $*)
-  echo $filter
-  todoist l -f $filter
-}
-
-overdue() {
-  syncTodoist
-  declare -a filter=(overdue)
-  if [[ -z "$*" ]]; then
-    if [[ ! -z "${todoistProject}" ]]; then
-      filter+=("& #${todoistProject}")
-      echo "** Filtered to Project (via \$todoistProject): #${todoistProject}"
-    fi
-  else
-    for i in $*; do
-      #echo $i
-      case $i in
-        (#*) filter+=("& $i")
-            ;;
-        (*) fitler+=($i)
-            ;;
-      esac
-      #echo ${filter}
-    done
-  fi
-  #echo ${filter}
-  todoist l -f "${filter}"
-}
-
-## Work specific, keep at bottom
-if [ -f ~/.zshrc.work ]; then source ~/.zshrc.work; fi
-
